- hosts: all
  vars_files:
    - 'defaults/main.yml'  
  tasks:
    - name: install the dependencies
      apt:
        pkg: "{{item}}"
        state: present
      with_items: ["perl", "libperl-dev", "build-essential"]
    - include: 'tasks/main.yml'

  handlers:
    - include: 'handlers/main.yml'
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted
      when: rabbitmq_install == "yes" 
