# configure_rabbitmq.yml
 
  - name: RabbitMQ | Ensuring python-software-properties is installed
    apt: pkg=python-software-properties state=installed

  - name: RabbitMQ | Adding rabbitmq official apt repository
    apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

  - name: RabbitMQ | Installing rabbitmq
    apt: pkg=rabbitmq-server={{rabbitmq_version}} state=installed force=yes

  - name: RabbitMQ | Enabling rabbitmq plugins
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
    notify:
    - restart rabbitmq

  - name: RabbitMQ | Adding admin and user account
    rabbitmq_user: user={{item}} password=changeme tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
    with_items:
    - admin
    - user

  - name: RabbitMQ | Removing default guest user
    rabbitmq_user: user=guest state=absent

  - name: RabbitMQ | Ensuring vhost /test is present
    rabbitmq_vhost: name=/test state=present

  - name: Nginx Plus | Updating the Nginx tcp stream configuration for RabbitMQ
    template:
      src: nginx_plus_rabbitmq.conf.j2
      dest: "{{nginx_dir}}/stream.d/rabbitmq.conf"
      owner: root
      group: root
      mode: 0644
    notify:
      - restart nginx
