# configure.yml

- name: Nginx | Updating mime.types file
  copy:
    src: mime.types
    dest: "{{nginx_dir}}/mime.types"
    owner: root
    group: root
    mode: 0644

# check and update the configuration files

- name: Nginx | Checking for an existing nginx.conf file
  stat:
    path: "{{nginx_dir}}/nginx.conf"
  register: nginx_config

# Nginx plus template updates when default site is requested
#
- include: configure_nginx.yml
  when: nginx_default_site == "yes"

# Nginx Plus update used when nginx plus template is requested

- include: configure_plus.yml
  when: nginx_plus_default_site == "yes"

# rabbit mq install used to demo tcp upstream withing Nginx Plus

- include: configure_rabbitmq.yml
  when: rabbitmq_install == "yes"

# start nginx for the first time

- name: Nginx | Starting Nginx for the first time
  service:
    name: nginx
    state: started
  register: nginx_first_start
  when: not nginx_config.stat.exists
