# configure_plus.yml

- name: Nginx Plus | Updating the nginx.conf file from template
  template:
    src: nginx_plus_nginx.conf.j2
    dest: "{{nginx_dir}}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Nginx Plus | Updating the conf.d/default.conf file from template
  template:
    src: nginx_plus_default.conf.j2
    dest: "{{nginx_dir}}/conf.d/default.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
