# default_site.yml

- name: Nginx | Ensuring the default site root directory is present
  file:
    path: "{{nginx_default_root}}"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0754

- name: Nginx | Checking for existing index.html
  stat:
    path: "{{nginx_default_root}}/index.html"
  register: nginx_default_index

- name: Nginx | Copying placeholder index.html
  copy:
    src: "index.html"
    dest: "{{nginx_default_root}}/index.html"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
  when: not nginx_default_index.stat.exists

- name: Nginx | Reload if we just created index.html
  service:
    name: nginx
    state: reloaded
  when: not nginx_default_index.stat.exists
