- name: Nginx | Make sure the Nginx configuration is updated
  template:
    src: nginx_plus_nginx.conf.j2
    dest: "{{nginx_dir}}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Nginx | Make sure the Nginx configuration is updated
  template:
    src: nginx_plus_default.conf.j2
    dest: "{{nginx_dir}}/conf.d/default.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- include: rabbitmq.yml
  when: rabbitmq_install == "yes"

