# nginx plus

# IMPORTANT: 	all steps in this block require a valid trial or commercial license of the Nginx Plus product
# 	      	along with a copy of the nginx repo certificate and public key provided by Nginx Inc
#
#		https://www.nginx.com/products/
#		1-800-915-9122

- name: Nginx Plus | Creating Nginx Plus ssl cert repo directory
  file: path=/etc/ssl/nginx state=directory group=root mode=0700

- name: Nginx Plus | Copy Nginx Plus repository certificate
  copy: src=/etc/ssl/nginx/nginx-repo.crt dest=/etc/ssl/nginx/nginx-repo.crt owner=root group=root mode=0700

- name: Nginx Plus | Copy Nginx Plus repository key
  copy: src=/etc/ssl/nginx/nginx-repo.key dest=/etc/ssl/nginx/nginx-repo.key owner=root group=root mode=0700

- name: Nginx Plus | Downloading Nginx Plus CA certificate
  get_url: url=https://cs.nginx.com/static/files/CA.crt dest=/etc/ssl/nginx/CA.crt mode=0700 validate_certs=no

- name: Nginx Plus | Downloading yum Nginx Plus repository
  get_url: url=https://cs.nginx.com/static/files/nginx-plus-7.repo dest=/etc/yum.repos.d/nginx-plus-7.repo mode=0700 validate_certs=no

- name: Nginx Plus | Making sure the ansible required dependencies are installed
  yum:
    name: python-pycurl
    state: present

- name: Nginx Plus | Installing Nginx Plus
  yum:
    name: nginx-plus
    state: latest
  notify:
    - restart nginx

- include: directories.yml
