# file: nginx/tasks/user.yml

- name: Nginx | Making sure the nginx group is present
  group:
    gid: "{{nginx_gid}}"
    name: "{{nginx_group}}"
    state: present

- name: Nginx | Making sure the www directory is present
  file:
    path: "{{nginx_www_dir}}"
    state: directory

- name: Nginx | Making sure the nginx user is present
  user:
    name: "{{nginx_user}}"
    uid: "{{nginx_uid}}"
    group: "{{nginx_group}}"
    comment: "Nginx user"
    home: "{{nginx_www_dir}}"
    shell: /bin/false
    state: present
    system: yes

- name: Nginx | Setting the right directory permissions for the www directory
  file:
    path: "{{nginx_www_dir}}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
    state: directory

- name: Nginx | Checking the current password expiry
  command: grep {{nginx_user}} /etc/shadow
  sudo: yes
  register: nginx_old_password
  changed_when: false

- name: Nginx | Setting the right expiration on the nginx user
  shell: "chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{nginx_user}} && grep {{nginx_user}} /etc/shadow"
  sudo: yes
  register: nginx_new_password
  changed_when: nginx_new_password.stdout != nginx_old_password.stdout
