# file: nginx/handlers/main.yml

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes
  when: not nginx_first_start.changed

- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes

- name: stop nginx
  service: name=nginx state=stopped
  sudo: yes

